use_frameworks!

target 'AlisNetworking_Example' do
  pod 'AlisNetworking', :path => '../'
  pod 'AEDataKit'

  target 'AlisNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
