use_frameworks!

target 'AlisNetworking_Example' do
  pod 'AlisNetworking', :path => '../'

  target 'AlisNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'AEDataKit'
  end
end
